homeassistant:
  # Name of the location where Home Assistant is running
  name: RV-201801-2
  # Location required to calculate the time the sun rises and sets
  latitude: 43.352111
  longitude: -8.264065
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 15
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# Tracked history is kept for 10 days
recorder:
  purge_keep_days: 10

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

google:
 client_id: 388489724376-2kcihdbsrsolvr81l1jqn7273t31iqm8.apps.googleusercontent.com
 client_secret: FnRmyUQ2O847Xg_eft4yT8z2

panel_iframe:
 terminal:
  title: Terminal
  icon: mdi:console
  url: http://riovao.es:7681

 configurador:
  title: Configurador
  icon: mdi:wrench
  url: http://riovao.es:3218
  
camera:
  - platform: onvif
    host: 192.168.1.118

# Weather prediction
sensor:
  - platform: yr

  - platform: command_line
    name: Temp. CPU Raspberry
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(2) }}'

  - platform: yweather
    monitored_conditions:
      - weather
      - weather_current
      - temp_min
      - temp_max
      - wind_speed
      - pressure
      - visibility
      - humidity
      - temperature
      
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

  - platform: speedtest
    minute: 30
    monitored_conditions:
      - ping
      - download
      - upload

  - platform: worldclock
    time_zone: America/Los_Angeles

  - platform: qnap
    host: 192.168.1.101
    port: 444
    verify_ssl: true
    username: admin
    password: Luisas123
    monitored_conditions:
     - status
     - cpu_usage
     - memory_percent_used
     - network_tx
     - network_rx
     - volume_percentage_used

media_player:
  - platform: plex

  - platform: kodi
    host: 192.168.1.104

  - platform: webostv
    host: 192.168.1.113
    mac: C8:08:E9:B3:47:60
    name: TV Sala
    customize:
      sources:
        - livetv
        - youtube
        - makotv

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    home_interval: 10

notify:
  - platform: webostv
    host: 192.168.0.113
    name: sala-tv

  - name: GMAIL-LGL
    platform: smtp
    server: smtp.gmail.com
    port: 587
    sender: riovao62b@gmail.com
    starttls: true
    username: riovao62b@gmail.com
    password: Sada20051973
    recipient: lglinares@gmail.com 

light:
  - platform: hyperion
    host: 192.168.1.104
    
switch:
  - platform: orvibo
    discovery: true
    switches:
    -  host: 192.168.1.122
       name: Manta-Maria

# Text to speech
tts:
  - platform: google
  
zwave:
  usb_path: /dev/ttyACM0
  
# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

####################################################################################
#    ZONES       Iconos de zonas en https://materialdesignicons.com/               #
####################################################################################

zone:
  name: Indra
  latitude: 43.344784
  longitude: -8.431445
  radius: 100
  icon: mdi:factory

zone 2:
  name: Hospital
  latitude: 43.344190
  longitude: -8.388353
  radius: 200
  icon: mdi:hospital-building

zone 3:
  name: Betanzos
  latitude: 43.280068
  longitude: -8.213073
  radius: 200
  icon: mdi:home-variant

zone 4:
  name: Chantada
  latitude: 42.609086
  longitude: -7.772940
  radius: 200
  icon: mdi:home-variant
